### ISSUE TITLE
Is everyone an admin? 

### ISSUE THREAD

**Issue by secretgspot** [j4w8n/sveltekit-supabase-oauth#4]
How does it differentiate between authenticated user and an admin that has service_role.

**Comment by j4w8n** [comment]
I haven't built any role-based logic in. So, for the purposes of the example, anyone who can login to GitHub is an authenticated user.

**Comment by secretgspot** [comment]
> I haven't built any role-based logic in. So, for the purposes of the example, anyone who can login to GitHub is an authenticated user.

aah, thanks for prompt reply.. do you know or have an idea how role based could be implemented to give admin service_role access and restrict from certain areas of the site such as admin route?

**Comment by j4w8n** [comment]
Unfortunately no. Not something I've experimented with yet.
